const tips = [
	"Eat three healthy meals a day (breakfast, lunch, and dinner); it is important to remember that dinner does not have to be the largest meal.",
	"The bulk of food consumption should consist of healthy foods, such as fruits, vegetables, whole grains, and fat-free or low-fat milk products.",
	"Incorporate lean meats, poultry, fish, beans, eggs, and nuts (with emphasis on beans and nuts) into a healthy diet.",
	"Control portion sizes; eat the smallest portion that can satisfy hunger and then stop eating",
	"Healthy snacks are OK in moderation and should consist of items like fruit, whole grains, or nuts to satisfy hunger and not cause excessive weight gain.",
	"Avoid eating a large meal before sleeping to decrease gastroesophageal reflux and weight gain.",
	"If a person is angry or depressed, eating will not solve these situations and may make the underlying problems worse.",
	"Avoid eating raw or undercooked meats of any type.",
	"People with unusual work schedules (night shifts, college students, military) should try to adhere to a breakfast, lunch, and dinner routine with minimal snacking.",
	"People trying to lose weight (body fat) should avoid all fatty and sugary foods and eat mainly vegetables, fruits, and nuts and markedly reduce his/her intake of meat and dairy products",
	"Regular exercise can help increase self-esteem and self-confidence, decrease stress and anxiety, enhance mood, and improve general mental health.",
	"Regular exercise can help control body weight and in some people cause loss of fat.",
	"Exercise can be broken up into smaller 10-minute sessions.",
	"Almost any type of exercise (resistance, water aerobics, walking, swimming, weights, yoga, and many others) is helpful for everybody.",
	"Take a walk and reflect on what you see and hear at least several times per week.",
	"Try something new and often (eat a new food, try a different route to work, go to a new museum display).",
	"Do some mind exercises (read, do a puzzle occasionally during the week).",
	"Try to focus on a process intensely and complete a segment of it over 1 to several hours, then take a break and do something relaxing (walk, exercise, short nap).",
	"Plan to spend some time talking with other people about different subjects.",
	"Have fun (go on a trip with someone you love, go shopping, go fishing; do not let vacation time slip away).",
	"Let yourself be pleased with your achievements, both big and small (develop contentment).",
	"Have a network of friends; those with strong social support systems lead healthier lives.",
	"Seek help and advice early if you feel depressed, have suicidal thoughts, or consider harming yourself or others.",
	'People taking medicine for mental health problems should not stop taking these medications, no matter how "well" they feel, until they have discussed their situation with their prescribing doctor(s)',
	"Vary your meals. When the cafeteria has your favorite foods daily it can be easy to return to those old favorites every day. Changing up your diet from day to day is an important part of good nutrition so take advantage of the variety of selections available to you.",
	"Eat breakfast. Start your day off right with a good meal when you get up. Whether you’re rolling out of bed at noon or up at the crack of dawn for class, make sure you start your day with a balanced, healthy meal.",
	"Don’t fight stress by eating. It can be tempting to reach for a bag of chips or some cookies when you’re stressed out about an impending exam. Eating won’t help your stress go away, so avoid filling up on snacks. Try working out or taking a break instead.",
	"Drink water. Drinking enough water can help boost your concentration as well as keep you from overeating. Make sure to keep hydrated as you go through your day by bringing water with you.",
	"Try to eat fruits and veggies. Even if fruits and vegetables don’t comprise some of your favorite foods, try to incorporate at least a few of them into your diet each day.",
	"Make it convenient to eat right. Don’t make it hard for yourself to eat right. Buy healthy foods and stock your fridge and room with them to ensure they’re the first things at hand when you get hungry.",
	"Indulge every once in awhile. A little treat now and then is a great way to reward yourself for eating a healthy diet. Give yourself a break and indulge in a food you love but can’t eat all the time.",
	"Stretch first. Help yourself avoid injuries by stretching each time you exercise. Simple stretches before and after you work out or engage in physical activity can help keep you active and pain free.",
	"Play a sport. One way to get yourself motivated to exercise is to make it a game by playing a sport. Join an intramural team or play recreational sports through your school to get active and have fun at the same time.",
	"Walk to class. While taking public transportation might be quicker, walking will give you a chance to stretch your legs, burn some calories and relax before your next class.",
	"Make it fun. You’re probably not going to work out if you are bored with your routine or find going to the gym torture. Find a way to make it fun for yourself and you’ll be much more likely to keep it up.",
	"Take a nap. If you have the time during the day, a short nap can do wonders for your energy levels. Just make sure not to nap too close to bedtime or for too long, and a nap will do your body good.",
	"Don’t work in bed. Working in bed can make getting to sleep harder. Keep your work space separate from your sleep space to keep insomnia at bay.",
	"Get a full night’s rest whenever possible. While the amount of sleep each person needs varies, most people need 7-9 hours to feel fully rested. While this may not be possible every night, try to sleep a full night whenever you get the chance.",
	"Stick to a schedule. With different classes and work hours each day, it can be hard to stick to a schedule, but keeping sleep times similar from day to day can greatly improve your chances of getting a good night’s sleep.",
	"Understand that lack of sleep can have a big impact. Lack of sleep doesn’t just make you cranky, it can also reduce your ability to concentrate and to excel at class, so try to get as much sleep as you need.",
	"Work out bedtimes with roommates. When sharing a room with someone it can be hard to go to bed when you need to and not get woken up when you don’t want to. Try to work with your roomies to make sure you each get the sleep you need.",
	"Avoid all nighters. While you may feel like you need to study all night to do well you might be doing yourself a disservice. Not getting enough sleep can impair your ability to do well, regardless of how much you’ve studied, so make sure you get at least a little sleep before your big test.",
	"Create a bedtime routine. If you have trouble falling asleep at night you can help yourself by creating a routine that will let your mind and body know that bedtime is approaching and that it should get into sleep mode. After a few weeks of practice this should help you fall asleep when you need to.",
	"Avoid caffeine, eating and drinking right before bed. All of these activities can throw off your body’s internal clock, so try to limit meals, alcohol and caffeine consumption to a few hours before bed.",
	"Keep your room dark and quiet. While college campuses are hardly either, try to keep your room as dark, quiet and cool as possible. This will help trigger to your body that it’s time for bed and help you get and stay asleep.",
	"Wash your hands. Studies have shown that simple hand washing can help prevent a large number of illnesses. So wash your hands, especially any time you’ll be touching your nose, mouth or eyes or if you’ve been around others who are sick.",
	"Get to the doctor. If you have symptoms that aren’t showing any signs of clearing up within a few days, you may need to take a trip to the campus clinic or your doctor. Simple illnesses can mutate into much more deadly and dangerous ones if left alone so make sure to seek help if you aren’t feeling any better.",
	"Drink lots of fluids. Colds and flu can wreck havoc on your body, often depriving it of much needed fluids. Replenish these by drinking plenty of water or energy drinks when you’re ill.",
	"Wear flip flops in the shower. Dorm bathrooms are generally cleaned daily, but can become dirty quickly with so many students sharing them. Always make sure to wear sandals in the shower to avoid getting viruses and bacteria that can cause warts and athlete’s foot.",
	"Don’t touch your eyes, nose or mouth. If your hands aren’t totally clean, try to avoid touching these areas. The membranes in these areas make it easy for bacteria and viruses to enter your body.",
	"Try simple over the counter remedies. Most viruses leave you feeling miserable but with no recourse in medications that can make them go away. Try out over the counter remedies to help ease your symptoms.",
	"Put limits on work hours. You can’t work all the time-fun and relaxation have to be part of your routine as well. Limit the times when you will work to give yourself time to sleep and rest up so you won’t get sick.",
	"Give yourself a break. If you’ve been working steadily for hours, give your eyes and mind a chance for a rest by taking a break. You can come back feeling more refreshed and ready to go.",
	"Be realistic. Sometimes there’s just no way you’re going to get done everything you’d like to in one day. Be realistic about your goals and understand that you can only do so much.",
	"Understand you can’t do everything. While you might want to go to class, work, play a sport, and participate in clubs and social activities, the reality is that sooner or later you’re going to get run down by trying to do so much. Focus on doing the things you truly love and forget about the rest.",
	"Get help. If you’re feeling overwhelmed, reach out and ask for help from professors and friends. They may be able to give you more time or help you to complete projects and studying more quickly.",
	"Relax with hobbies. Whether you like to paint or to destroy aliens with your friends in video games, making time for the things you love is an important part of keeping yourself from getting too stressed out.",
	"Give yourself plenty of time. It’s easy to put off starting on a big project or studying for a test until the last minute. You’ll be much less stressed out, however, and will likely do better if you give yourself more time to work on it.",
	"Spend time with friends. There are few things that can cheer you up like being around the people you like most. Eat dinner with friends or just hang out and watch tv or take a walk to get away from the stress of homework.",
	"Don’t let yourself get run down. With so much to do, it’s easy to get run down. If you feel yourself getting stretched too thin, take a step back and evaluate everything you’ve got going on to determine what’s really important.",
	"Learn time management skills. Time management skills will make everything from getting assignments done to managing work a lot easier. Read a book or check out advice on the internet, to help you better manage the hours of your day."
];

const generateTip = () => {
	return tips[Math.floor(Math.random() * tips.length)];
};

export default generateTip;
